name: Deploy to AWS EC2

on:
  push:
    branches:
      - main  # Triggers workflow on push to the main branch

jobs:
  deploy:
    runs-on: self-hosted  # Ensure your EC2 instance is configured as a self-hosted runner

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Use Node.js 16 or later

    - name: Install Dependencies
      run: npm install

    - name: Run Unit Tests
      run: npm test

    - name: Run Integration Tests
      run: |
        echo "Running integration tests..."
        npm run test:integration || (echo "Integration tests failed!" && exit 1)

    - name: Ensure Docker is Running
      run: sudo systemctl start docker || true  # Ensure Docker daemon is running

    - name: Build Docker Image
      run: docker build -t my-html-app .

    - name: Stop and Remove Old Container (if exists)
      run: |
        docker stop my-html-container || true
        docker rm my-html-container || true

    - name: Run New Docker Container
      run: |
        docker run -d -p 8080:80 --name my-html-container my-html-app

    - name: Wait for Container to Initialize
      run: sleep 30  # Increased wait time to ensure Nginx starts

    - name: Check Running Containers
      run: |
        docker ps -a
        docker logs my-html-container || true

    - name: Verify Deployment
      run: |
        echo "Checking if the web server is running..."
        RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8080)
        if [[ "$RESPONSE" -ne 200 ]]; then
          echo "Deployment Failed! Expected HTTP 200, got $RESPONSE"
          exit 1
        fi
        echo "Deployment Successful!"
